In [5]:
import numpy as np

# Parameters
alpha = 0.1
beta = 0.4
n = 50

# Transition matrix
P = np.array([
    [1 - alpha, alpha],
    [beta, 1 - beta]  
])

# Compute P^n
Pn = np.linalg.matrix_power(P, n)

print("P^50 =")
print(Pn)

# Analytical steady-state
pi_silence = beta / (alpha + beta)
pi_speech = alpha / (alpha + beta)

P_inf = np.array([
    [pi_silence, pi_speech],
    [pi_silence, pi_speech]
])

print("\nAnalytical P^inf =")
print(P_inf)

error = np.abs(Pn - P_inf)

print("\nError =")
print(error)

P^50 =
[[0.8 0.2]
 [0.8 0.2]]

Analytical P^inf =
[[0.8 0.2]
 [0.8 0.2]]

Error =
[[2.10942375e-15 2.77555756e-16]
 [1.22124533e-15 1.16573418e-15]]


In [6]:
import numpy as np

alpha = 0.1
beta = 0.4
steps = 100000

# Transition matrix
P = np.array([
    [1 - alpha, alpha],
    [beta, 1 - beta]  
])

state = 0  # start in silence
counts = [0, 0]

for _ in range(steps):
    counts[state] += 1
    state = np.random.choice([0, 1], p=P[state])

# Empirical probabilities
pi_empirical = np.array(counts) / steps

print("Empirical steady state:")
print(pi_empirical)

Empirical steady state:
[0.8018 0.1982]
